[app]
title = SOS 69069 PQID
package.name = sos69069pqid
package.domain = com.sos69069
source.dir = .
source.include_exts = py,png,jpg,kv,atlas,json,txt
version = 1.6.9
android.numeric_version = 169069
orientation = portrait
fullscreen = 0
presplash.filename = %(source.dir)s/presplash.png
icon.filename = %(source.dir)s/icon.png
android.permissions = INTERNET
android.api = 31
android.minapi = 21
android.ndk = 25b
android.accept_sdk_license = True
android.archs = arm64-v8a
requirements = python3,kivy,requests,urllib3,certifi,charset-normalizer,idna
preset = 1
